services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: graphql_books
      MYSQL_USER: root
      MYSQL_PASSWORD: hari0412
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: